import ToasterContext from '@/context/ToasterContext'
import '@/app/globals.css'
import { Inter } from 'next/font/google'
import AuthContext from '@/context/AuthContext'
import Sidebar from '@/components/sidebar/Sidebar'
import getUsers from '../actions/getUsers'
import UserList from '@/components/UserList'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'EchoChat',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const users = await getUsers()
    return (
        <Sidebar>
            <div className="h-full">
                <UserList users={users}/>
                {children}
            </div>
        </Sidebar>
    )
}

